{{- if .Values.manifests.configmap_env }}
{{- $context := . }}
{{- $keystone_auth_host := tuple $context "keystone" | include "contrail-helper.get_endpoint_host" }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-vrouter
data:
  CONTROLLER_NODES: {{ .Values.conf.controller_nodes }}
  LOG_LEVEL: {{ .Values.conf.log_level }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-vrouter-auth
data:
  CLOUD_ORCHESTRATOR: {{ .Values.conf.cloud_orchestrator }}
  AAA_MODE: {{ .Values.conf.aaa_mode }}
  KEYSTONE_AUTH_ADMIN_USER: {{ .Values.endpoints.identity.auth.admin.username }}
  KEYSTONE_AUTH_ADMIN_TENANT: {{ .Values.endpoints.identity.auth.admin.project_name }}
  KEYSTONE_AUTH_ADMIN_PASSWORD: {{ .Values.endpoints.identity.auth.admin.password }}
  KEYSTONE_AUTH_USER_DOMAIN_NAME: {{ .Values.endpoints.identity.auth.admin.user_domain_name }}
  KEYSTONE_AUTH_PROJECT_DOMAIN_NAME: {{ .Values.endpoints.identity.auth.admin.project_domain_name }}
  KEYSTONE_AUTH_URL_VERSION: {{ .Values.endpoints.identity.path.default }}
  KEYSTONE_AUTH_HOST:
  KEYSTONE_AUTH_PROTO: {{ .Values.endpoints.identity.scheme.default }}
  KEYSTONE_AUTH_ADMIN_PORT: {{ .Values.endpoints.identity.port.admin.default | quote }}
  KEYSTONE_AUTH_PUBLIC_PORT: {{ .Values.endpoints.identity.port.api.default | quote }}

{{- end }}
